(() => {
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  const loadCss=(href)=>{if(document.querySelector(`link[href*="${href.split('?')[0]}"]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)};
  loadCss('luxury.css?v=1.1');
  loadCss('architecture.css?v=1.2');

  if(!$('#pageProgress')) document.body.insertAdjacentHTML('afterbegin','<div class="page-progress" aria-hidden="true"><span id="pageProgress"></span></div><div class="cursor-light" id="cursorLight" aria-hidden="true"></div>');

  const hero=$('.hero'), heroMedia=$('.hero-media'), heroShade=$('.hero-shade'), heroPanel=$('.hero-panel');
  if(heroMedia) heroMedia.id='heroMedia';
  if(heroPanel) heroPanel.id='heroPanel';
  if(hero&&!$('.hero-grain',hero)) heroShade?.insertAdjacentHTML('afterend','<div class="hero-grain" aria-hidden="true"></div><div class="hero-rail" aria-hidden="true"><span>ARCHITECTURAL GLASS</span><i></i><span>JUIZ DE FORA · MG</span></div>');
  const kicker=$('.hero .kicker'), heroTitle=$('.hero h1'), heroLead=$('.hero-copy>p');
  if(kicker) kicker.innerHTML='<span></span> ARQUITETURA EM VIDRO · JUIZ DE FORA';
  if(heroTitle) heroTitle.innerHTML='Vista livre.<br><em>Presença mínima.</em>';
  if(heroLead) heroLead.textContent='Fechamento de varandas pensado para proteger o ambiente sem competir com a arquitetura — com transparência, abertura e leitura visual limpa.';
  if(heroPanel) heroPanel.innerHTML='<div class="panel-top"><small>ARCHITECTURAL EXPERIENCE</small><span>01 / 03</span></div><div class="panel-signature">VIDRO<br><em>EM MOVIMENTO</em></div><div class="panel-line"></div><div class="panel-metric"><small>LEITURA DO AMBIENTE</small><strong>Amplitude preservada</strong></div><div class="panel-metric"><small>ABERTURA</small><strong>Painéis deslizantes e recolhíveis</strong></div><div class="panel-foot"><span class="live-dot"></span> AVALIAÇÃO TÉCNICA · JUIZ DE FORA</div>';

  const credibility=$('.credibility-strip');
  if(credibility&&!$('.visual-manifesto')) credibility.insertAdjacentHTML('afterend',`
    <section class="manifesto-strip" aria-label="Conceito do projeto"><div class="manifesto-track"><span>TRANSPARÊNCIA</span><i></i><span>PROTEÇÃO</span><i></i><span>ABERTURA</span><i></i><span>ARQUITETURA</span><i></i><span>CONFORTO</span><i></i><span>TRANSPARÊNCIA</span></div></section>
    <section class="section visual-manifesto"><div class="container visual-manifesto-grid"><div class="manifesto-statement reveal"><span class="manifesto-number">01</span><p class="eyebrow">MENOS ESTRUTURA. MAIS PAISAGEM.</p><h2>A vista continua.<br><em>O espaço evolui.</em></h2></div><div class="manifesto-image reveal delay-1"><div class="manifesto-image-overlay"><small>FECHAMENTO DE VARANDA</small><strong>Integração visual como ponto de partida.</strong></div></div><div class="manifesto-copy reveal delay-2"><p>Um projeto de fechamento pode proteger contra as condições externas sem transformar a varanda em um ambiente visualmente pesado. A proposta é equilibrar uso, movimento e transparência.</p><a href="#projetos">Explorar projetos <span>↗</span></a></div></div></section>
    <section class="brand-dossier" id="marca"><div class="container brand-dossier-head"><span class="brand-dossier-index reveal">02</span><div class="reveal delay-1"><p class="eyebrow">IDENTIDADE · PRESENÇA · PRECISÃO</p><h2>Uma marca apresentada com a mesma <em>precisão visual</em> que o produto exige.</h2></div><p class="brand-dossier-copy reveal delay-2">A experiência digital passa a se comportar como um material de arquitetura: menos ruído, mais hierarquia, mais espaço para obra, detalhe e informação técnica.</p></div><div class="container brand-canvas reveal"><div class="brand-canvas-mark" aria-hidden="true"><i></i><i></i><i></i></div><div class="brand-canvas-name"><small>CORTINA DE VIDRO</small><strong>JUIZ DE FORA</strong></div><div class="brand-canvas-meta"><span>ARQUITETURA EM VIDRO</span><span>FECHAMENTO DE VARANDAS</span><span>JF · MG</span></div><div class="brand-canvas-grid" aria-hidden="true"></div></div></section>`);

  const editorialIndex=$('.editorial-index span'); if(editorialIndex) editorialIndex.textContent='03';

  const projectGrid=$('.project-grid');
  if(projectGrid&&!projectGrid.classList.contains('project-grid-v12')){
    projectGrid.classList.add('project-grid-v12');
    $$('.project-card',projectGrid).forEach((card,i)=>{
      const key=String(i+1).padStart(2,'0');card.dataset.projectCard=key;
      if(!$('.project-hit',card)) card.insertAdjacentHTML('afterbegin',`<button class="project-hit" type="button" data-project="${key}" aria-label="Abrir case ${key}"></button>`);
      const img=$('.project-image',card); if(img&&!$('.project-open',img)) img.insertAdjacentHTML('beforeend','<span class="project-open">ABRIR CASE ↗</span>');
      const small=$('.project-caption small',card); if(small) small.textContent=`CASE ${key} · ${i===2?'FECHAMENTO':'RESIDENCIAL'}`;
    });
    projectGrid.insertAdjacentHTML('beforeend','<article class="project-card project-wide reveal" data-project-card="04"><button class="project-hit" type="button" data-project="04" aria-label="Abrir case 04"></button><div class="project-image image-d"><span class="image-label">OBRA PUBLICADA · DEMONSTRAÇÃO</span><span class="project-open">ABRIR CASE ↗</span></div><div class="project-caption"><div><small>CASE 04 · ARQUITETURA</small><h3>Continuidade de fachada</h3></div><span>04</span></div></article>');
  }

  const system=$('.system-section');
  if(system&&!$('#engenharia')) system.insertAdjacentHTML('afterend',`
    <section class="engineering" id="engenharia"><div class="container engineering-head"><div class="engineering-title reveal"><p class="eyebrow">ENGENHARIA DO MOVIMENTO</p><h2>O detalhe técnico entra em cena <em>sem perder a elegância.</em></h2></div><div class="engineering-intro reveal delay-1"><p>Uma leitura conceitual do sistema para explicar materiais, abertura e manutenção com linguagem clara. Dados dimensionais e especificações finais entram somente após validação da empresa.</p><span>VISUALIZAÇÃO CONCEITUAL · NÃO É DESENHO EXECUTIVO</span></div></div><div class="container engineering-layout"><div class="engineering-drawing reveal"><div class="drawing-grid" aria-hidden="true"></div><div class="drawing-axis drawing-axis-x"></div><div class="drawing-axis drawing-axis-y"></div><div class="drawing-label label-a"><span>01</span><strong>PAINÉIS DESLIZANTES</strong></div><div class="drawing-label label-b"><span>02</span><strong>RECOLHIMENTO</strong></div><div class="drawing-label label-c"><span>03</span><strong>LEITURA SEM MONTANTES VERTICAIS</strong></div><div class="engineering-track" id="engineeringTrack"><span></span><span></span><span></span><span></span><span></span><span></span></div><div class="engineering-control"><div><small>ABERTURA CONCEITUAL</small><strong id="openingLabel">0%</strong></div><input id="openingRange" type="range" min="0" max="100" value="0" aria-label="Simular abertura conceitual dos painéis"><div class="control-scale"><span>FECHADO</span><span>RECOLHIDO</span></div></div></div><aside class="engineering-specs reveal delay-1"><article><span>01</span><div><small>MATERIAL PUBLICADO</small><h3>Perfis em alumínio</h3><p>O FAQ atual da empresa informa perfis desenvolvidos 100% em alumínio.</p></div></article><article><span>02</span><div><small>COMPONENTES PUBLICADOS</small><h3>Roldanas em aço inox e nylon</h3><p>Materiais apresentados conforme informação publicada pela própria empresa.</p></div></article><article><span>03</span><div><small>LINGUAGEM DO SISTEMA</small><h3>Sem esquadrias verticais</h3><p>O fechamento preserva uma leitura visual contínua entre os painéis.</p></div></article><article><span>04</span><div><small>MANUTENÇÃO</small><h3>Limpeza pelo lado interno</h3><p>A abertura para dentro é destacada pela empresa como facilitadora da limpeza.</p></div></article></aside></div></section>`);

  const navLinks=$$('.nav-links a'); if(navLinks[3]){navLinks[3].textContent='Engenharia';navLinks[3].href='#engenharia'}
  const mobileLinks=$$('#mobileNav a'); if(mobileLinks[3]){mobileLinks[3].textContent='Engenharia';mobileLinks[3].href='#engenharia'}
  const finalTitle=$('.final-content h2'); if(finalTitle) finalTitle.innerHTML='A arquitetura permanece.<br><em>O vidro quase desaparece.</em>';
  const finalLead=$('.final-content>p:not(.eyebrow)'); if(finalLead) finalLead.textContent='Organize as informações do seu ambiente e avance para uma avaliação técnica com mais contexto.';

  if(!$('#projectModal')) $('#toast')?.insertAdjacentHTML('beforebegin','<div class="project-modal" id="projectModal" aria-hidden="true" role="dialog" aria-modal="true" aria-labelledby="projectModalTitle"><div class="project-modal-backdrop" data-modal-close></div><div class="project-modal-shell"><button class="project-modal-close" type="button" data-modal-close aria-label="Fechar case">Fechar <span>×</span></button><div class="project-modal-media" id="projectModalMedia"></div><div class="project-modal-content"><div class="project-modal-kicker"><span id="projectModalIndex">CASE 01</span><small>OBRA PUBLICADA · DEMONSTRAÇÃO</small></div><h2 id="projectModalTitle">Varanda panorâmica</h2><p id="projectModalText">Apresentação editorial preparada para receber informações reais do projeto após validação da empresa.</p><div class="project-modal-data"><div><small>TIPO</small><strong id="projectModalType">Fechamento de varanda</strong></div><div><small>LOCALIZAÇÃO</small><strong>Dados a validar</strong></div><div><small>DETALHES TÉCNICOS</small><strong>Dados a validar</strong></div></div><p class="project-modal-note">Nenhuma metragem, cliente, condomínio ou desempenho foi atribuído a esta obra sem validação.</p></div></div></div>');
  if(!$('.floating-visit')) $('#toast')?.insertAdjacentHTML('beforebegin','<a class="floating-visit" href="#simulador" aria-label="Agendar avaliação"><span>Agendar avaliação</span><i>↗</i></a>');

  const header=$('.site-header'), menuBtn=$('#menuBtn'), mobileNav=$('#mobileNav'), toast=$('#toast'), progress=$('#pageProgress'), cursor=$('#cursorLight'), floating=$('.floating-visit');
  const onScroll=()=>{const y=scrollY;header?.classList.toggle('scrolled',y>24);floating?.classList.toggle('visible',y>Math.min(innerHeight*.72,650));if(progress){const max=Math.max(document.documentElement.scrollHeight-innerHeight,1);progress.style.width=`${Math.min(100,y/max*100)}%`}if(heroMedia&&y<innerHeight*1.2&&!reduced)heroMedia.style.transform=`scale(1.045) translate3d(0,${Math.min(y*.055,44)}px,0)`};onScroll();addEventListener('scroll',onScroll,{passive:true});
  if(matchMedia('(pointer:fine)').matches&&!reduced){document.body.classList.add('has-pointer');addEventListener('pointermove',e=>{if(cursor){cursor.style.left=`${e.clientX}px`;cursor.style.top=`${e.clientY}px`}if(heroPanel&&scrollY<innerHeight){const x=(e.clientX/innerWidth-.5)*8,y=(e.clientY/innerHeight-.5)*8;heroPanel.style.transform=`translate3d(${x}px,${y}px,0)`}},{passive:true})}
  menuBtn?.addEventListener('click',()=>{const o=mobileNav?.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(!!o))});$$('#mobileNav a').forEach(a=>a.addEventListener('click',()=>mobileNav?.classList.remove('open')));

  const reveals=$$('.reveal'); if('IntersectionObserver'in window&&!reduced){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.1});reveals.forEach(el=>io.observe(el))}else reveals.forEach(el=>el.classList.add('visible'));
  $$('.faq-list details').forEach(item=>item.addEventListener('toggle',()=>{if(item.open)$$('.faq-list details').forEach(o=>{if(o!==item)o.open=false})}));

  const systemDemo=$('#systemDemo'),systemLabel=$('#systemLabel'),tabs=$$('.system-tab'),labels={closed:'Painéis fechados',slide:'Painéis em movimento',open:'Painéis recolhidos'};let si=0,touched=false;const setState=i=>{if(!tabs.length)return;si=(i+tabs.length)%tabs.length;tabs.forEach(t=>t.classList.remove('active'));const t=tabs[si];t.classList.add('active');const s=t.dataset.systemState||'closed';if(systemDemo)systemDemo.dataset.state=s;if(systemLabel)systemLabel.textContent=labels[s]};tabs.forEach((t,i)=>t.addEventListener('click',()=>{touched=true;setState(i)}));if(!reduced)setInterval(()=>{if(!touched&&document.visibilityState==='visible')setState(si+1)},3400);

  const range=$('#openingRange'),openingLabel=$('#openingLabel'),panels=$$('#engineeringTrack span');const renderOpen=v=>{const o=Math.max(0,Math.min(100,+v))/100;if(openingLabel)openingLabel.textContent=`${Math.round(o*100)}%`;panels.forEach((p,i)=>{const pos=i/Math.max(panels.length-1,1),e=Math.max(0,Math.min(1,(o-pos*.08)/.68));p.style.transform=`translateX(${e*i*6.2}%) scaleX(${1-e*.79})`;p.style.marginRight=`${-e*12.7}%`;p.style.opacity=String(1-e*.08)})};range?.addEventListener('input',e=>renderOpen(e.target.value));renderOpen(range?.value||0);

  const modal=$('#projectModal'),media=$('#projectModalMedia'),mIndex=$('#projectModalIndex'),mTitle=$('#projectModalTitle'),mText=$('#projectModalText'),mType=$('#projectModalType');let trigger=null;const projects={'01':['Varanda panorâmica','Fechamento de varanda','3','Uma leitura editorial da obra para destacar transparência, relação com a paisagem e continuidade visual. Informações específicas entram somente após validação da empresa.'],'02':['Integração visual','Fechamento de varanda','4','A fotografia assume o protagonismo e o projeto é apresentado como arquitetura, não como simples item de catálogo. Localização e escopo permanecem a validar.'],'03':['Proteção + abertura','Fechamento de varanda','5','A apresentação valoriza o equilíbrio entre fechamento, abertura e leitura limpa do ambiente, sem atribuir desempenho ou medidas não confirmadas.'],'04':['Continuidade de fachada','Arquitetura em vidro','6','Case preparado para receber contexto arquitetônico, detalhes construtivos e informações reais da obra quando aprovadas pela Cortina de Vidro JF.']};const openModal=k=>{const p=projects[k];if(!modal||!p)return;mIndex.textContent=`CASE ${k}`;mTitle.textContent=p[0];mType.textContent=p[1];mText.textContent=p[3];media.style.backgroundImage=`url('https://cortinadevidrojf.com.br/wp-content/uploads/2026/02/Cortina-de-Vidro-em-Juiz-de-Fora-${p[2]}.webp')`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');$('.project-modal-close',modal)?.focus()};const closeModal=()=>{modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');trigger?.focus()};$$('[data-project]').forEach(b=>b.addEventListener('click',()=>{trigger=b;openModal(b.dataset.project)}));$$('[data-modal-close]').forEach(b=>b.addEventListener('click',closeModal));addEventListener('keydown',e=>{if(e.key==='Escape'&&modal?.classList.contains('open'))closeModal()});

  const form=$('#glassForm');if(!form)return;const steps=$$('.form-step[data-step]:not([data-step="result"])',form),resultStep=$('.form-step[data-step="result"]',form),next=$('#nextBtn'),back=$('#backBtn'),simProgress=$('#simProgress'),counter=$('#stepCounter'),stepLabel=$('#stepLabel'),summary=$('#resultSummary'),meter=$('#meterRange'),meterValue=$('#meterValue'),phoneInput=$('#leadPhone');if(!steps.length||!resultStep||!next||!back||!simProgress||!counter||!stepLabel||!summary)return;
  const state={property:'',shape:'',meters:'10 m²',goal:'',timeline:'',result:false};let current=0;const showToast=m=>{if(!toast)return;toast.textContent=m;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2500)};const active=()=>state.result?resultStep:steps[current];const update=()=>{[...steps,resultStep].forEach(s=>s.classList.remove('active'));const a=active();a.classList.add('active');const n=state.result?6:current+1;simProgress.style.width=`${n/6*100}%`;counter.textContent=state.result?'PRONTO':`0${n} / 06`;stepLabel.textContent=a.dataset.label||'';back.disabled=current===0&&!state.result;next.innerHTML=state.result?'Solicitar avaliação no WhatsApp <span>→</span>':current===5?'Gerar resumo <span>→</span>':'Continuar <span>→</span>'};const choose=b=>{const g=b.dataset.group;if(!g||!(g in state))return;$$(`[data-group="${g}"]`,form).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state[g]=b.dataset.value||''};$$('[data-group]',form).forEach(b=>b.addEventListener('click',()=>choose(b)));meter?.addEventListener('input',e=>{const v=+e.target.value;if(meterValue)meterValue.textContent=v===50?'50+':String(v);state.meters=v===50?'50 m² ou mais':`${v} m²`});
  const validations=[()=>state.property?true:'Selecione o tipo de imóvel.',()=>state.shape?true:'Selecione o formato aproximado da varanda.',()=>true,()=>state.goal?true:'Selecione o principal objetivo.',()=>state.timeline?true:'Selecione quando pretende avançar.',()=>{const n=$('#leadName')?.value.trim()||'',c=$('#leadCity')?.value.trim()||'',p=$('#leadPhone')?.value.trim()||'',ok=!!$('#leadConsent')?.checked;if(!n||!c)return'Preencha seu nome e bairro/cidade.';if(p.replace(/\D/g,'').length<10)return'Informe um WhatsApp válido.';if(!ok)return'Confirme que deseja enviar estas informações.';return true}];
  const build=()=>{const items=[['IMÓVEL',state.property],['FORMATO',state.shape],['METRAGEM',state.meters],['OBJETIVO',state.goal],['PRAZO',state.timeline],['LOCAL',$('#leadCity')?.value.trim()||''],['CONTATO',$('#leadPhone')?.value.trim()||'']];summary.replaceChildren();items.forEach(([l,v])=>{const d=document.createElement('div'),s=document.createElement('small'),b=document.createElement('strong');d.className='result-item';s.textContent=l;b.textContent=v;d.append(s,b);summary.append(d)})};const whatsapp=()=>{const msg=['Olá! Vim pelo site e gostaria de solicitar uma avaliação para fechamento de varanda.','',`Tipo de imóvel: ${state.property}`,`Formato da varanda: ${state.shape}`,`Metragem aproximada: ${state.meters}`,`Principal objetivo: ${state.goal}`,`Prazo: ${state.timeline}`,`Nome: ${$('#leadName')?.value.trim()||''}`,`Bairro/cidade: ${$('#leadCity')?.value.trim()||''}`,`Meu WhatsApp: ${$('#leadPhone')?.value.trim()||''}`,'','Gostaria de entender os próximos passos para uma visita técnica.'].join('\n');window.open(`https://wa.me/5532984810470?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer')};next.addEventListener('click',()=>{if(state.result){whatsapp();return}const v=validations[current]?.();if(v!==true){showToast(v||'Revise esta etapa.');return}if(current<steps.length-1){current++;update();return}build();state.result=true;update()});back.addEventListener('click',()=>{if(state.result){state.result=false;current=steps.length-1;update();return}if(current>0){current--;update()}});phoneInput?.addEventListener('input',e=>{let v=e.target.value.replace(/\D/g,'').slice(0,11);if(v.length>6)v=`(${v.slice(0,2)}) ${v.slice(2,7)}-${v.slice(7)}`;else if(v.length>2)v=`(${v.slice(0,2)}) ${v.slice(2)}`;else if(v.length)v=`(${v}`;e.target.value=v});update();
})();
